config/routes.rb
Enki::Application.routes.draw do
  namespace :admin do
    resource :session

    resources :posts, :pages do
      post 'preview', :on => :collection
    end
    resources :comments
    resources :undo_items do
      post 'undo', :on => :member
    end

    get 'health(/:action)' => 'health', :action => 'index', :as => :health
    post 'health/generate_exception' => 'health#generate_exception'

    root :to => 'dashboard#show'
  end

  resources :archives, :only => [:index]
  resources :pages, :only => [:show]

  constraints :year => /\d{4}/, :month => /\d{2}/, :day => /\d{2}/ do
    get ':year/:month/:day/:slug/comments'  => 'comments#index'
    post ':year/:month/:day/:slug/comments' => 'comments#create'
    get ':year/:month/:day/:slug/comments/new' => 'comments#new'
    get ':year/:month/:day/:slug' => 'posts#show'
  end

  scope :to => 'posts#index' do
    get 'posts.:format', :as => :formatted_posts
    get '(:tag)', :as => :posts, :tag => /(?:[A-Za-z0-9_ \.-]|%20)+?/, :format => /html|atom/
  end

  # OmniAuth routes.
  post 'auth/open_id_comment/callback', :to => 'comments#create'
  match 'auth/failure' => 'comments#create',
  :constraints => lambda { |request|
    request.query_parameters[:strategy] == ApplicationController::OMNIAUTH_OPEN_ID_COMMENT_STRATEGY
  }, :via => [:get]
  post 'auth/open_id_admin/callback', :to => 'admin/sessions#create'
  match 'auth/:provider/callback', :to => 'admin/sessions#create', :via => [:get, :post]
  get 'auth/failure/comments/new', :to => 'comments#new'
  get 'auth/failure', :to => 'admin/sessions#new'

  root :to => 'posts#index'
end

app/views/admin/pages/_form.html.erb
<%= form.inputs do -%>
  <%= form.input :title %>
  <%= form.input :slug, :hint => "Leave blank for an auto-generated slug based on the title." %>
  <%= form.input :body, :hint => "<a href='http://textile.thresholdstate.com/'>Textile enabled</a>. Use Ctrl+E to switch between preview and edit mode.".html_safe %>
<% end -%>

app/views/admin/pages/_page.html.erb
<tr class="<%= cycle('', 'alt') %>">
  <td><%= page.created_at.strftime('%d %b, %Y') %></td>
  <td><%= link_to(page.title, admin_page_path(page)) %></td>
  <td><%= truncate(page.body, :length => 50) %></td>
  <td><%= page.slug %></td>
  <td>
    <%= link_to(image_tag('silk/pencil.png', :alt => 'edit'), admin_page_path(page)) %>
    <%= form_for(page, :as => :page, :url => admin_page_path(page), :html => {:class => 'delete-item', :method => :delete}) do |form| -%>
      <%= image_submit_tag("silk/delete.png", :alt => 'Delete Comment') %>
    <% end -%>
  </td>
</tr>

app/views/admin/pages/index.html.erb
<h1>Your pages</h1>

<table id='pages'>
  <thead>
    <tr>
      <th>Created At</th>
      <th>Title</th>
      <th>Excerpt</th>
      <th>Link</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @pages.empty? -%>
      <tr><td colspan="5">There are no pages at this time.</td></tr>
    <% else -%>
      <%= render :partial => 'page', :collection => @pages %>
    <% end -%>
  </tbody>

  <tfoot>
    <% if @pages.total_pages > 1 -%>
      <tr class="pagination">
        <td colspan='5'>
          <%= will_paginate(@pages, :previous_label => '« Newer', :next_label => 'Older »') %>
        </td>
      </tr>
    <% end -%>
  </tfoot>
</table>

app/views/admin/pages/new.html.erb
<h1>New page</h1>

<%= semantic_form_for([:admin, @page]) do |form| -%>
  <%= render :partial => 'form', :locals => {:form => form} %>
  <%= form.actions do -%>
    <%= form.action :submit, :as => :button -%>
  <% end -%>
<% end -%>

app/views/admin/pages/show.html.erb
<h1>Editing page - <%= link_to(@page.title, page_path(@page.slug)) %></h1>

<%= semantic_form_for([:admin, @page]) do |form| -%>
  <%= render :partial => 'form', :locals => {:form => form} %>
  <%= form.actions do -%>
    <%= form.action :submit, :as => :button -%>
  <% end -%>
<% end -%>