config/routes.rb
Enki::Application.routes.draw do
  namespace :admin do
    resource :session

    resources :posts, :pages do
      post 'preview', :on => :collection
    end
    resources :comments
    resources :undo_items do
      post 'undo', :on => :member
    end

    get 'health(/:action)' => 'health', :action => 'index', :as => :health
    post 'health/generate_exception' => 'health#generate_exception'

    root :to => 'dashboard#show'
  end

  resources :archives, :only => [:index]
  resources :pages, :only => [:show]

  constraints :year => /\d{4}/, :month => /\d{2}/, :day => /\d{2}/ do
    get ':year/:month/:day/:slug/comments'  => 'comments#index'
    post ':year/:month/:day/:slug/comments' => 'comments#create'
    get ':year/:month/:day/:slug/comments/new' => 'comments#new'
    get ':year/:month/:day/:slug' => 'posts#show'
  end

  scope :to => 'posts#index' do
    get 'posts.:format', :as => :formatted_posts
    get '(:tag)', :as => :posts, :tag => /(?:[A-Za-z0-9_ \.-]|%20)+?/, :format => /html|atom/
  end

  # OmniAuth routes.
  post 'auth/open_id_comment/callback', :to => 'comments#create'
  match 'auth/failure' => 'comments#create',
  :constraints => lambda { |request|
    request.query_parameters[:strategy] == ApplicationController::OMNIAUTH_OPEN_ID_COMMENT_STRATEGY
  }, :via => [:get]
  post 'auth/open_id_admin/callback', :to => 'admin/sessions#create'
  match 'auth/:provider/callback', :to => 'admin/sessions#create', :via => [:get, :post]
  get 'auth/failure/comments/new', :to => 'comments#new'
  get 'auth/failure', :to => 'admin/sessions#new'

  root :to => 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  DEFAULT_LIMIT = 15

  acts_as_taggable

  has_many                :comments, :dependent => :destroy
  has_many                :approved_comments, :class_name => 'Comment'

  before_validation       :generate_slug
  before_validation       :set_dates
  before_save             :apply_filter

  validates               :title, :slug, :body, :presence => true

  validate                :validate_published_at_natural

  def validate_published_at_natural
    if published_at_natural.present? && !published?
      errors.add("published_at_natural", "Unable to parse time")
    end
  end

  attr_accessor :minor_edit
  def minor_edit
    @minor_edit ||= "1"
  end

  def minor_edit?
    self.minor_edit == "1"
  end

  def published?
    published_at?
  end

  attr_accessor :published_at_natural
  def published_at_natural
    @published_at_natural ||= published_at.send_with_default(:strftime, '', "%Y-%m-%d %H:%M")
  end

  class << self
    def build_for_preview(params)
      post = Post.new(params)
      post.generate_slug
      post.set_dates
      post.apply_filter
      TagList.from(params[:tag_list]).each do |tag|
        post.tags << Tag.new(:name => tag)
      end
      post
    end

    def find_recent(options = {})
      tag = options.delete(:tag)
      include_tags = options[:include] == :tags
      order = 'published_at DESC'
      conditions = ['published_at < ?', Time.zone.now]
      limit = options[:limit] ||= DEFAULT_LIMIT

      options = {
        :order      => order,
        :conditions => conditions,
        :limit      => limit
      }.merge(options)

      if tag
        find_tagged_with(tag, options)
      else
        result = where(conditions)
        result = result.includes(:tags) if include_tags
        result.order(order).limit(limit)
      end
    end

    def find_by_permalink(year, month, day, slug, options = {})
      begin
        day = Time.parse([year, month, day].collect(&:to_i).join("-")).midnight
        result = where(['slug = ?', slug])

        if !options.empty? && options[:include].present?
          result = result.includes(:approved_comments) if options[:include].include?(:approved_comments)
          result = result.includes(:tags) if options[:include].include?(:tags)
        end

        post = result.detect do |post|
          [:year, :month, :day].all? {|time|
            post.published_at.send(time) == day.send(time)
          }
        end
      rescue ArgumentError # Invalid time
        post = nil
      end
      post || raise(ActiveRecord::RecordNotFound)
    end

    def find_all_grouped_by_month
      posts = where(['published_at < ?', Time.now]).order('published_at DESC')
      month = Struct.new(:date, :posts)
      posts.group_by(&:month).inject([]) {|a, v| a << month.new(v[0], v[1])}
    end
  end

  def destroy_with_undo
    transaction do
      undo = DeletePostUndo.create_undo(self)
      self.destroy
      return undo
    end
  end

  def month
    published_at.beginning_of_month
  end

  def apply_filter
    self.body_html = EnkiFormatter.format_as_xhtml(self.body)
  end

  def set_dates
    self.edited_at = Time.now if self.edited_at.nil? || !minor_edit?
    unless self.published_at_natural.nil?
      if self.published_at_natural.blank?
        self.published_at = nil
      elsif new_published_at = Chronic.parse(self.published_at_natural)
        self.published_at = new_published_at
      end
    end
  end

  def denormalize_comments_count!
    update_column(:approved_comments_count, self.approved_comments.count)
  end

  def generate_slug
    self.slug = self.title.dup if self.slug.blank?
    self.slug.slugorize!
  end

  def tag_list=(value)
    value = value.split(',') if value.is_a?(String)
    value.map!{ |tag_name| Tag::filter_name(tag_name) }

    # TODO: Contribute this back to acts_as_taggable_on_steroids plugin
    value = value.join(", ") if value.respond_to?(:join)
    super(value)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_filter :find_post, :only => [:show, :update, :destroy]

  def index
    respond_to do |format|
      format.html {
        @posts = Post.paginate(:page => params[:page]).order("coalesce(published_at, updated_at) DESC")
      }
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      respond_to do |format|
        format.html {
          flash[:notice] = "Created post '#{@post.title}'"
          redirect_to(:action => 'show', :id => @post)
        }
      end
    else
      respond_to do |format|
        format.html { render :action => 'new', :status => :unprocessable_entity }
      end
    end
  end

  def update
    if @post.update_attributes(post_params)
      respond_to do |format|
        format.html {
          flash[:notice] = "Updated post '#{@post.title}'"
          redirect_to(:action => 'show', :id => @post)
        }
      end
    else
      respond_to do |format|
        format.html { render :action => 'show', :status => :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |format|
      format.html {
        render :partial => 'post', :locals => {:post => @post} if request.xhr?
      }
    end
  end

  def new
    @post = Post.new
  end

  def preview
    @post = Post.build_for_preview(post_params)

    respond_to do |format|
      format.js {
        render :partial => 'posts/post', :locals => {:post => @post}
      }
    end
  end

  def destroy
    undo_item = @post.destroy_with_undo

    respond_to do |format|
      format.html do
        flash[:notice] = "Deleted post '#{@post.title}'"
        redirect_to :action => 'index'
      end
      format.json {
        render :json => {
          :undo_path    => undo_admin_undo_item_path(undo_item),
          :undo_message => undo_item.description,
          :post         => @post.attributes
        }
      }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :tag_list, :published_at_natural, :slug, :minor_edit)
  end

  protected

  def find_post
    @post = Post.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @tag = params[:tag]
    @posts = Post.find_recent(:tag => @tag, :include => :tags)

    raise(ActiveRecord::RecordNotFound) if @tag && @posts.empty?

    respond_to do |format|
      format.html
      format.atom { render :layout => false }
    end
  end

  def show
    @post = Post.find_by_permalink(*([:year, :month, :day, :slug].collect {|x| params[x] } << {:include => [:approved_comments, :tags]}))
    @comment = Comment.new
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  # This isn't strictly correct, but it's a pretty good guess
  # and saves another hit to the DB
  def more_content?
    @posts.size == Post::DEFAULT_LIMIT
  end
end

app/views/posts/_post.html.erb
<h2><%= link_to_post(post) %></h2>

<div class="entry-body">
  <%= raw(post.body_html) %>
</div>
<div class="meta">
  <ul>
    <li class="date">Posted on <%= format_post_date(post.published_at) if post.published? %></li>
    <li class="comments"><%= link_to_post_comments post %></li>
    <% unless post.tags.empty? -%>
      <li class="tags">Tagged <%= linked_tag_list(post.tags) %></li>
    <% end -%>
  </ul>
</div>

app/views/posts/index.html.erb
<% content_for :page_title do -%>
  <%= posts_title(@tag) %>
<% end -%>

<% content_for :head do -%>
  <%= auto_discovery_link_tag(:atom, @tag.nil? ? formatted_posts_path(:format => 'atom') : posts_path(:tag => @tag, :format => 'atom')) %>
<% end -%>

<% if @posts.empty? -%>
	<p>There are no posts yet.</p>
<% else -%>
	<% @posts.each do |post| -%>
	<div class="post" id="<%= dom_id(post) %>">
	  <%= render post %>
	</div>
	<% end -%>
  <% if more_content? -%>
    <div class="related">Looking for more? Head on over to the <%= link_to 'archives', archives_path %>.</div>
  <% end -%>
<% end -%>

app/views/posts/show.html.erb
<% content_for :page_title do -%>
  <%= post_title @post -%>
<% end -%>

<%= render @post %>

<ol id="comments" class="commentlist">
  <% @post.approved_comments.each do |comment| -%>
    <li<%=raw cycle(' class="alt"', '') %> id="comment-<%= comment.id %>">
      <%= render comment %>
    </li>
  <% end -%>
</ol>

<div class="related">Looking for more? Head on over to the <%= link_to 'archives', archives_path %>.</div>

<h2>Post a comment</h2>
<% unless @comment.errors.empty? -%>
<div class="errors">
  <h3>Comment not added!</h3>
  <ul>
    <% @comment.errors.sort_by(&:first).each do |error| -%>
      <li><%= format_comment_error(error) %></li>
    <% end -%>
  </ul>
</div>
<% end -%>

<div>
  <%= form_for [@post, @comment], :url => post_comments_path(@post, @comment) do |form| -%>
    <p>
      <%= form.text_field 'author' %>
      <%= form.label :author %>
      <small>Name or <%= link_to 'OpenID', 'http://openidexplained.com/' %> (required)</small>
    </p>
    <p>
      <%= form.text_area 'body' %><br/>
      <small>(<%= link_to 'lesstile enabled', 'http://lesstile.rubyforge.org' %> - surround code blocks with ---)</small>
    </p>
    <p><%= form.submit 'Add Comment' %></p>
  <% end -%>
</div>