config/routes.rb
Enki::Application.routes.draw do
  namespace :admin do
    resource :session

    resources :posts, :pages do
      post 'preview', :on => :collection
    end
    resources :comments
    resources :undo_items do
      post 'undo', :on => :member
    end

    get 'health(/:action)' => 'health', :action => 'index', :as => :health
    post 'health/generate_exception' => 'health#generate_exception'

    root :to => 'dashboard#show'
  end

  resources :archives, :only => [:index]
  resources :pages, :only => [:show]

  constraints :year => /\d{4}/, :month => /\d{2}/, :day => /\d{2}/ do
    get ':year/:month/:day/:slug/comments'  => 'comments#index'
    post ':year/:month/:day/:slug/comments' => 'comments#create'
    get ':year/:month/:day/:slug/comments/new' => 'comments#new'
    get ':year/:month/:day/:slug' => 'posts#show'
  end

  scope :to => 'posts#index' do
    get 'posts.:format', :as => :formatted_posts
    get '(:tag)', :as => :posts, :tag => /(?:[A-Za-z0-9_ \.-]|%20)+?/, :format => /html|atom/
  end

  # OmniAuth routes.
  post 'auth/open_id_comment/callback', :to => 'comments#create'
  match 'auth/failure' => 'comments#create',
  :constraints => lambda { |request|
    request.query_parameters[:strategy] == ApplicationController::OMNIAUTH_OPEN_ID_COMMENT_STRATEGY
  }, :via => [:get]
  post 'auth/open_id_admin/callback', :to => 'admin/sessions#create'
  match 'auth/:provider/callback', :to => 'admin/sessions#create', :via => [:get, :post]
  get 'auth/failure/comments/new', :to => 'comments#new'
  get 'auth/failure', :to => 'admin/sessions#new'

  root :to => 'posts#index'
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
  <meta charset="utf-8">

  <title><%= enki_config[:title] %> - Admin</title>

  <%= csrf_meta_tag %>

  <%= javascript_include_tag 'admin' %>

  <%= stylesheet_link_tag 'admin' %>
  <%= yield(:head) %>

  <% if flash[:notice] -%>
    <%= javascript_tag do -%>
      $(function() {
        humanMsg.displayMsg('<%= escape_javascript(flash[:notice]) %>');
      })
    <% end -%>
  <% end -%>

</head>
<body>
  <div id="page">
    <div id="content">
      <%= yield %>
    </div>
    <div id="nav">
      <ul>
        <li><%= nav_link_to("Dashboard", admin_root_path,       :accesskey => '1') %></li>
        <li><%= nav_link_to("Posts",     admin_posts_path,      :accesskey => '2') %> <%= nav_link_to("(+)", new_admin_post_path, :accesskey => 'n') %></li>
        <li><%= nav_link_to("Pages",     admin_pages_path,      :accesskey => '3') %> <%= nav_link_to("(+)", new_admin_page_path, :accesskey => 'p') %></li>
        <li><%= nav_link_to("Comments",  admin_comments_path,   :accesskey => '4') %></li>
        <li><%= nav_link_to("Actions",   admin_undo_items_path, :accesskey => '5') %></li>
        <li><%= nav_link_to("Health",    admin_health_path,     :accesskey => '6') %></li>
        <li class="separator">&nbsp;</li>
        <li><%= link_to("Logout", admin_session_path, :accesskey => 'l', :method => :delete) %></li>
        <li><%= link_to("View Site", root_path,       :accesskey => 'v', :title => 'View Site') %></li>
      </ul>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
  <meta charset="utf-8">
  <title><%= html_title yield(:page_title) %></title>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= open_id_delegation_link_tags(enki_config[:open_id_delegation, :server], enki_config[:open_id_delegation, :delegate]) if enki_config[:open_id_delegation] %>
  <%= yield(:head) %>
</head>
<body>
  <div id="page_container">
    <div id="content">
      <h1 id="page_heading"><a href="<%= root_url %>"><%= enki_config[:title] %></a></h1>

      <div id="main">
        <%= yield %>
      </div>

      <div id="navigation">
        <h2>Pages</h2>
        <ul>
          <% page_links_for_navigation.each do |link| -%>
            <li><%= link_to(link.name, link.url) %></li>
          <% end -%>
        </ul>
        <% unless category_links_for_navigation.empty? -%>
          <h2>Categories</h2>
          <ul>
            <% category_links_for_navigation.each do |link| -%>
              <li><%= link_to(link.name, link.url) %></li>
            <% end -%>
          </ul>
        <% end -%>
        <form method="get" id="sform" action="http://www.google.com/search">
          <div>
            <h2><label for="q">Search</label></h2>

            <input type="text" id="q" value="" name="q">
            <input type="hidden" name="sitesearch" value="<%= enki_config[:url] %>">
          </div>
        </form>
      </div>

      <div id="footer"><%= enki_config[:title] %> &#169; <%= enki_config[:author, :name] %>. Valid <a href="http://validator.w3.org/check?uri=referer">HTML5</a> and <%= link_to "ATOM", "http://feedvalidator.org/check.cgi?url=#{enki_config[:url]}/posts.atom" %>. Powered by <a href="http://www.enkiblog.com" title="A Ruby on Rails blogging app for the fashionable developer">Enki</a>.</div>
    </div>
  </div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>
  <meta charset="utf-8">
  <title><%= enki_config[:title] %> - Admin Login</title>
  <%= stylesheet_link_tag 'login' %>
  <%= javascript_tag do -%>
    // Why is this code here? After a failed OpenID login, second and subsequent tries will cause Rails to throw an
    // ActionDispatch::Cookies::CookieOverflow exception when hitting the /auth/open_id_admin path (this path is
    // dynamically set by OmniAuth) due to the large amount of stuff passed in from the query string. So let's
    // automagically say goodbye to the query string, no one needs it in this case anyway.
    if (window.location.href.indexOf('/auth/open_id_admin/callback?') > -1) {
      window.history.pushState(null, 'Look ma! No query string!', '/auth/open_id_admin/callback');
    }
  <% end -%>
</head>
<body>
  <div id="page">
    <div id="content">
      <%= yield %>
    </div>
    <div id="nav">
      <ul>
        <li><%= link_to 'View Site', root_path, :title => 'View Site' %></li>
      </ul>
    </div>
  </div>
</body>
</html>